# Generated by Django 5.1.7 on 2025-03-12 11:33

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('post', '0004_alter_post_description_alter_post_header_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='userpostrelation',
            old_name='in_bookmarks',
            new_name='is_bookmark',
        ),
    ]
